# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title                    : "HiSD Package: soluscape-1.0"
email: liuyuyang@stu.pku.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
  A Python package for constructing solution landscapes using High-index Saddle Dynamics (HiSD).
baseurl: "/soluscape" # the subpath of your site, e.g. /blog
url: "https://hisdpackage.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
atom_feed:
  hide: true

repository: HiSDpackage/soluscape
repository_tree: main

# Build settings
# theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
search: true
search_full_content: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  highlighter: rouge
  # syntax_highlighter: rouge // new version, github pages need the old one
permalink   : date

#comments:
# provider: "disqus"
# disqus:
#  shortname: "https-hisdpackage-github-io"

include:
  - _Tutorial
  - _Examples
  - _Background
  - _HiSD
  - _GHiSD
  - _AHiSD
  - _Contact

exclude:
  - doc/
  - soluscape-1.0/
  - README.md
  - requirements.txt
  - gallery/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

## => Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache

# Defaults
defaults:
  # _Tutorial: for Tutorial documents
  - scope:
      path: "_Tutorial"
      type: pages
    values:
      layout: single
      author_profile: false
      share: false
      comments: true
      sidebar:
        nav: "Tutorial"
      mathjax: true
      toc: true
      toc_sticky: true  
   # _Examples: for Examples documents
  - scope:
      path: "_Examples"
      type: pages
    values:
      layout: single
      author_profile: false
      share: false
      comments: true
      sidebar:
        nav: "Examples"
      mathjax: true
      toc: true
      toc_sticky: true  
  # _Background: for Background documents
  - scope:
      path: "_Background"
      type: pages
    values:
      layout: single
      author_profile: false
      share: false
      comments: true
      sidebar:
        nav: "Theory"
      mathjax: true
      toc: true
      toc_sticky: true    
  # _HiOSD: for HiSD documents
  - scope:
      path: "_HiSD"
      type: pages
    values:
      layout: single
      author_profile: false
      share: false
      comments: true
      sidebar:
        nav: "Theory"
      mathjax: true
      toc: true
      toc_sticky: true
  # _GHiSD: for GHiSD documents
  - scope:
      path: "_GHiSD"
      type: pages
    values:
      layout: single
      author_profile: false
      share: false
      comments: true
      sidebar:
        nav: "Theory"
      mathjax: true
      toc: true
      toc_sticky: true
  # _AHiSD: for AHiSD documents
  - scope:
      path: "_AHiSD"
      type: pages
    values:
      layout: single
      author_profile: false
      share: false
      comments: true
      sidebar:
        nav: "Theory"
      mathjax: true
      toc: true
      toc_sticky: true


# Outputting
permalink: /:categories/:title/

category_archive:
  type: liquid
  path: /categories/
